author: Chromium Authors <mojo-dev@googlegroups.com>
dependencies:
  args: '>=0.13.0 <1.0.0'
  path: '>=1.3.5 <2.0.0'
description: Placeholder for mojom bindings.
environment:
  sdk: '>=1.9.0 <2.0.0'
homepage: https://github.com/domokit/mojo
name: mojom
version: 0.0.10
